#!/bin/bash
set -ex
cd data
hg pull
hg up
cd ..
./preprocess
anolis --output-encoding=ascii --omit-optional-tags --enable=xspecxref \
	--w3c-compat-xref-a-placement --use-strict intermediate.html editing.html
rm intermediate.html
sed -i 's!<span class=secno>[^<]*</span>!!g' editing.html
