#!/usr/bin/python

# This script is probably evil, but I am unspeakably sick of typing stuff like
# <span data-anolis-spec=domcore title=concept-element-namespace>namespace</span>.

replace = {
    "bpnode": "<span data-anolis-spec=domrange title=concept-boundary-point-node>node</span>",
    "bpnodes": "<span data-anolis-spec=domrange title=concept-boundary-point-node>nodes</span>",
    "bpoffset": "<span data-anolis-spec=domrange title=concept-boundary-point-offset>offset</span>",
    "bpoffsets": "<span data-anolis-spec=domrange title=concept-boundary-point-offset>offsets</span>",
    "comment": "<code data-anolis-spec=domcore>Comment</code>",
    "descendant": "<span data-anolis-spec=domcore title=concept-descendant-node>descendant</span>",
    "descendants": "<span data-anolis-spec=domcore title=concept-descendant-node>descendants</span>",
    "element": "<code data-anolis-spec=domcore>Element</code>",
    "index": "<span data-anolis-spec=domrange title=concept-indexof>index</span>",
    "namespace": "<span data-anolis-spec=domcore title=concept-element-namespace>namespace</span>",
    "node": "<code data-anolis-spec=domcore>Node</code>",
    "nodelength": "<code data-anolis-spec=domrange title=concept-node-length>length</code>",
    "processinginstruction": "<code data-anolis-spec=domcore>ProcessingInstruction</code>",
    "range": "<code data-anolis-spec=domrange>Range</code>",
    "rangeend": "<span data-anolis-spec=domrange title=concept-range-end>end</span>",
    "rangestart": "<span data-anolis-spec=domrange title=concept-range-start>start</span>",
    "text": "<code data-anolis-spec=domcore>Text</code>",
    "treeorder": "<span data-anolis-spec=domcore>tree order</span>",
}

s = open("source.html", "r").read()
for key in replace:
    s = s.replace("[[" + key + "]]", replace[key])

if "[[" in s:
    raise Exception("Something mistyped?  " + s[s.find("[["):s.rfind("]]") + 2])

f = open("intermediate.html", "w")
f.write(s)
f.close()
