#!/usr/bin/python

# This script is probably evil, but I am unspeakably sick of typing stuff like
# <span data-anolis-spec=domcore title=concept-element-namespace>namespace</span>.
# <var title> is also really pointless, although I should really get that fixed
# in Anolis proper.
import re

replace = {
    'a': '<code data-anolis-spec=html title="the a element">a</code>',
    'ancestor': '<span data-anolis-spec=domcore title=concept-tree-ancestor>ancestor</span>',
    'ancestorcontainer': '<span data-anolis-spec=domrange title="ancestor container">ancestor container</span>',
    'attrlocalname': '<span data-anolis-spec=domcore title=concept-attr-local-name>local name</span>',
    'attrvalue': '<span data-anolis-spec=domcore title=concept-attr-value>value</span>',
    'b': '<code data-anolis-spec=html title="the b element">b</code>',
    'blockquote': '<code data-anolis-spec=html title="the blockquote element">blockquote</code>',
    'br': '<code data-anolis-spec=html title="the br element">br</code>',
    'boundarypoint': '<span data-anolis-spec=domrange title=concept-boundary-point>boundary point</span>',
    'bpafter': '<span data-anolis-spec=domrange title=concept-bp-after>after</span>',
    'bpbefore': '<span data-anolis-spec=domrange title=concept-bp-before>before</span>',
    'bpnode': '<span data-anolis-spec=domrange title=concept-boundary-point-node>node</span>',
    'bpoffset': '<span data-anolis-spec=domrange title=concept-boundary-point-offset>offset</span>',
    'bpposition': '<span data-anolis-spec=domrange title=concept-bp-position>position</span>',
    'cddata': '<code data-anolis-spec=domcore title=dom-CharacterData-data>data</code>',
    'cdlength': '<code data-anolis-spec=domcore title=dom-CharacterData-length>length</code>',
    'child': '<span data-anolis-spec=domcore title=concept-tree-child>child</span>',
    'children': '<span data-anolis-spec=domcore title=concept-tree-child>children</span>',
    'collection': '<span data-anolis-spec=domcore title=concept-collection>collection</span>',
    'contained': '<span data-anolis-spec=domrange>contained</span>',
    'comment': '<code data-anolis-spec=domcore>Comment</code>',
    'compval': '<a href=http://www.w3.org/TR/CSS21/cascade.html#computed-value>computed value</a>',
    'contextobject': '<span data-anolis-spec=domrange>context object</span>',
    'descendant': '<span data-anolis-spec=domcore title=concept-tree-descendant>descendant</span>',
    'directionality': '<span data-anolis-spec=html title="the directionality">directionality</span>',
    'div': '<code data-anolis-spec=html title="the div element">div</code>',
    'dd': '<code data-anolis-spec=html title="the dd element">dd</code>',
    'dl': '<code data-anolis-spec=html title="the dl element">dl</code>',
    'dt': '<code data-anolis-spec=html title="the dt element">dt</code>',
    'document': '<code data-anolis-spec=domcore>Document</code>',
    'documentfragment': '<code data-anolis-spec=domcore>DocumentFragment</code>',
    'documenttype': '<code data-anolis-spec=domcore>DocumentType</code>',
    'element': '<code data-anolis-spec=domcore>Element</code>',
    'em': '<code data-anolis-spec=html title="the em element">em</code>',
    'endnode': '<span data-anolis-spec=domrange title=concept-range-end>end</span> <span data-anolis-spec=domrange title=concept-boundary-point-node>node</span>',
    'endoffset': '<span data-anolis-spec=domrange title=concept-range-end>end</span> <span data-anolis-spec=domrange title=concept-boundary-point-offset>offset</span>',
    'firstchild': '<code data-anolis-spec=domcore title=dom-Node-firstChild>firstChild</code>',
    'followingsibling': '<span data-anolis-spec=domcore title="concept-tree-following-sibling">following sibling</span>',
    'font': '<code data-anolis-spec=html title=font>font</code>',
    'fontcolor': '<code data-anolis-spec=html title=dom-font-color>color</code>',
    'fontface': '<code data-anolis-spec=html title=dom-font-face>face</code>',
    'fontsize': '<code data-anolis-spec=html title=dom-font-size>size</code>',
    'getselection': '<code data-anolis-spec=domrange title=dom-Document-getSelection>getSelection()</code>',
    'htmldocument': '<code data-anolis-spec=html>HTMLDocument</code>',
    'htmlnamespace': '<span data-anolis-spec=domcore>HTML namespace</span>',
    'hr': '<code data-anolis-spec=html title="the hr element">hr</code>',
    'href': '<code data-anolis-spec=html title=attr-hyperlink-href>href</code>',
    'i': '<code data-anolis-spec=html title="the i element">i</code>',
    'img': '<code data-anolis-spec=html title="the img element">img</code>',
    'index': '<span data-anolis-spec=domrange title=concept-indexof>index</span>',
    'lastchild': '<code data-anolis-spec=domcore title=dom-Node-lastChild>lastChild</code>',
    'length': '<span data-anolis-spec=domrange title=concept-node-length>length</span>',
    'li': '<code data-anolis-spec=html title="the li element">li</code>',
    'localname': '<span data-anolis-spec=domcore title=concept-element-local-name>local name</span>',
    'namespace': '<span data-anolis-spec=domcore title=concept-element-namespace>namespace</span>',
    'nextsibling': '<code data-anolis-spec=domcore title=dom-Node-nextSibling>nextSibling</code>',
    'node': '<span data-anolis-spec=domcore title=concept-node>node</span>',
    'nodelength': '<span data-anolis-spec=domrange title=concept-node-length>length</span>',
    'ol': '<code data-anolis-spec=html title="the ol element">ol</code>',
    'ownerdocument': '<code data-anolis-spec=domcore title=dom-Node-ownerDocument>ownerDocument</code>',
    'p': '<code data-anolis-spec=html title="the p element">p</code>',
    'parent': '<span data-anolis-spec=domcore title=concept-tree-parent>parent</span>',
    'partiallycontained': '<span data-anolis-spec=domrange>partially contained</span>',
    'phrasingcontent': '<span data-anolis-spec=html>phrasing content</span>',
    'precedingsibling': '<span data-anolis-spec=domcore title="concept-tree-preceding-sibling">preceding sibling</span>',
    'presentationalhint': '<span data-anolis-spec=html title="presentational hints">presentational hint</span>',
    'previoussibling': '<code data-anolis-spec=domcore title=dom-Node-previousSibling>previousSibling</code>',
    'range': '<span data-anolis-spec=domrange title=concept-range>range</span>',
    'rangeend': '<span data-anolis-spec=domrange title=concept-range-end>end</span>',
    'rangemutationrules': '<span data-anolis-spec=domrange>range mutation rules</span>',
    'rangeroot': '<span data-anolis-spec=domrange title=concept-range-root>root</span>',
    'rangestart': '<span data-anolis-spec=domrange title=concept-range-start>start</span>',
    'removeallranges': '<code data-anolis-spec=domrange title=dom-Selection-removeAllRanges>removeAllRanges()</code>',
    's': '<code data-anolis-spec=html title="the s element">s</code>',
    'selection': '<code data-anolis-spec=domrange>Selection</code>',
    'sibling': '<span data-anolis-spec=domcore title=concept-tree-sibling>sibling</span>',
    'spacecharacter': '<span data-anolis-spec=domcore title="space character">space character</span>',
    'span': '<code data-anolis-spec=html title="the span element">span</code>',
    'startnode': '<span data-anolis-spec=domrange title=concept-range-start>start</span> <span data-anolis-spec=domrange title=concept-boundary-point-node>node</span>',
    'startoffset': '<span data-anolis-spec=domrange title=concept-range-start>start</span> <span data-anolis-spec=domrange title=concept-boundary-point-offset>offset</span>',
    'strel': '<a href=http://es5.github.com/#x8.4>element</a>',
    'strike': '<code data-anolis-spec=html title="the strike element">strike</code>',
    'strlen': '<a href=http://es5.github.com/#x15.5.5.1>length</a>',
    'strong': '<code data-anolis-spec=html title="the strong element">strong</code>',
    'style': '<code data-anolis-spec=html title="the style attribute">style</code>',
    'sub': '<code data-anolis-spec=html title="the sub and sup elements">sub</code>',
    'sup': '<code data-anolis-spec=html title="the sub and sup elements">sup</code>',
    'table': '<code data-anolis-spec=html title="the table element">table</code>',
    'tbody': '<code data-anolis-spec=html title="the tbody element">tbody</code>',
    'td': '<code data-anolis-spec=html title="the td element">td</code>',
    'tfoot': '<code data-anolis-spec=html title="the tfoot element">tfoot</code>',
    'th': '<code data-anolis-spec=html title="the th element">th</code>',
    'thead': '<code data-anolis-spec=html title="the thead element">thead</code>',
    'tr': '<code data-anolis-spec=html title="the tr element">tr</code>',
    'text': '<code data-anolis-spec=domcore>Text</code>',
    'treeorder': '<span data-anolis-spec=domcore>tree order</span>',
    'u': '<code data-anolis-spec=html title="the u element">u</code>',
    'ul': '<code data-anolis-spec=html title="the ul element">ul</code>',
    'INVALID_ACCESS_ERR': '<code data-anolis-spec=domcore title=dom-DOMException-INVALID_ACCESS_ERR>INVALID_ACCESS_ERR</code>',
    'NOT_SUPPORTED_ERR': '<code data-anolis-spec=domcore title=dom-DOMException-NOT_SUPPORTED_ERR>NOT_SUPPORTED_ERR</code>',
    'SECURITY_ERR': '<code data-anolis-spec=domcore title=dom-DOMException-SECURITY_ERR>SECURITY_ERR</code>',
}

s = open("source.html", "r").read()
for key in replace:
    s = s.replace("[[" + key + "]]", replace[key])
    # Plurals
    s = s.replace("[[" + key + "s]]", replace[key].replace("</", "s</"))
    s = s.replace("[[" + key + "es]]", replace[key].replace("</", "es</"))
    # Capitals
    capreplace = replace[key].split(">")
    capreplace[1] = capreplace[1].capitalize()
    capreplace = ">".join(capreplace)
    s = s.replace("[[" + key.capitalize() + "]]", capreplace)

fnreplace = {
    'createelement': '<code data-anolis-spec=domcore title=dom-Document-createElement>createElement(\\1)</code>',
    'deletedata': '<code data-anolis-spec=domcore title=dom-CharacterData-deleteData>deleteData(\\1)</code>',
    'extend': '<code data-anolis-spec=domrange title=dom-Selection-extend>extend(\\1)</code>',
    'insertdata': '<code data-anolis-spec=domcore title=dom-CharacterData-insertData>insertData(\\1)</code>',
    'insertnode': '<code data-anolis-spec=domrange title=dom-Range-insertNode>insertNode(\\1)</code>',
    'replacedata': '<code data-anolis-spec=domcore title=dom-CharacterData-replaceData>replaceData(\\1)</code>',
    'selcollapse': '<code data-anolis-spec=domrange title=dom-Selection-collapse>collapse(\\1)</code>',
    'selectallchildren': '<code data-anolis-spec=domrange title=dom-Selection-selectAllChildren>selectAllChildren(\\1)</code>',
    'setattribute': '<code data-anolis-spec=domcore title=dom-Element-setAttribute>setAttribute(\\1)</code>',
}

for key in fnreplace:
    s = re.sub(r"\[\[" + key + "\|([^]]*)\]\]", fnreplace[key], s)

if "[[" in s:
    raise Exception("Something mistyped?  " + s[s.find("[["):s.rfind("]]") + 2])

s = s.replace("<var>", "<var title>")

s = s.replace("<!-- @{ -->", "")
s = s.replace("<!-- @} -->", "")
s = re.sub(r"\n<!-- vim:.*: -->", "", s)

f = open("intermediate.html", "w")
f.write(s)
f.close()
# vim: set textwidth=0:
