#!/usr/bin/python

import os.path
import sys

reverse = 0

if len(sys.argv) == 2 and sys.argv[1] == "--reverse":
	reverse = 1

files = [
	"webforms2.testsuite.org/controls/common-attributes/list/009.htm",
	"webforms2.testsuite.org/controls/common-attributes/pattern/009.htm",
	"webforms2.testsuite.org/controls/common-attributes/readonly/001.htm",
	"webforms2.testsuite.org/controls/common-attributes/readonly/003.htm",
	"webforms2.testsuite.org/controls/common-attributes/readonly/005.htm",
	"webforms2.testsuite.org/controls/common-attributes/required/002.htm",
	"webforms2.testsuite.org/controls/common-attributes/required/004.xht",
	"webforms2.testsuite.org/controls/common-attributes/required/006.htm",
	"webforms2.testsuite.org/controls/common-attributes/required/007.htm",
	"webforms2.testsuite.org/controls/radio/004.htm",
	"webforms2.testsuite.org/controls/url/001.htm",
	"webforms2.testsuite.org/elements/datalist/005.xht",
	"webforms2.testsuite.org/elements/datalist/006.xht",
	"webforms2.testsuite.org/elements/datalist/008.xht",
	"webforms2.testsuite.org/events/invalid/001.htm",
	"webforms2.testsuite.org/repetition/attributes/repeat/001.htm",
	"webforms2.testsuite.org/repetition/attributes/repeat/002.xht",
	"webforms2.testsuite.org/repetition/attributes/repeat/003.xht",
	"webforms2.testsuite.org/repetition/attributes/repeat-max/001.htm", #REVISIT
	"webforms2.testsuite.org/repetition/attributes/repeat-min/002.htm",
	"webforms2.testsuite.org/repetition/buttons/add/002.htm",
	"webforms2.testsuite.org/repetition/buttons/remove/002.htm",
	"webforms2.testsuite.org/submission/validation/willValidate/003.htm",
	"webforms2.testsuite.org/submission/validation/willValidate/007.xht",
	"webforms2.testsuite.org/submission/validation/willValidate/010.xht",
	"webforms2.testsuite.org/repetition/buttons/add/001.htm",
	"webforms2.testsuite.org/repetition/buttons/add/005.htm",
	"webforms2.testsuite.org/controls/date/001.htm",
	"webforms2.testsuite.org/controls/date/002.htm",
	"webforms2.testsuite.org/controls/date/003.htm",
	"webforms2.testsuite.org/controls/datetime/002.htm",
	"webforms2.testsuite.org/controls/datetime-local/001.htm",
	"webforms2.testsuite.org/controls/month/001.htm",
	"webforms2.testsuite.org/controls/number/004.htm",
	"webforms2.testsuite.org/events/invalid/003.xht",
	"webforms2.testsuite.org/controls/number/003.htm"
]

for file in files:
	if reverse:
		destination = "html5core-plus-web-forms2/valid/" + file
		source = "html5core-plus-web-forms2/invalid/" + file
	else:
		source = "html5core-plus-web-forms2/valid/" + file
		destination = "html5core-plus-web-forms2/invalid/" + file
		
	if os.path.exists(source):
		os.renames(source, destination)
