#!/bin/sh
# This is the script I use on my server to publish the spec.  It's not really
# useful for anyone else, I just want it in version control somewhere.
set -e
cd ~/webroot/spec/editing
git pull
git push github
cd ~/webroot/tmp/editing
git fetch --all
cd ~/webroot/spec
rm -rf hg-editing || true
hg clone ~/webroot/tmp/editing hg-editing
cd hg-editing
hg push -r master https://dvcs.w3.org/hg/editing
