#!/bin/sh
# Currently I cross-check data generation in Gecko and WebKit, then populate
# using the WebKit copy because it has fewer bugs to fix.  This fixes the bugs
# for me.  Must be run from the root of the spec repo.
set -e
cd conformancetest
fromdos webkit-data
fromdos gecko-data
diff -u webkit-data gecko-data | tail -n +3 > tmp-diff
diff -u tmp-diff diff
rm tmp-diff
cp webkit-data data.js
patch data.js patch
echo >> data.js
