// META: title=test WebNN API gemm operation
// META: global=window,dedicatedworker
// META: script=./resources/utils.js
// META: timeout=long

'use strict';

// https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-gemm

async function testGemm(operandType, syncFlag, pa, pb, expected, pc, options) {
  const a = builder.input('a', {type: operandType, dimensions: pa[1]});
  const TestTypedArray = TypedArrayDict[operandType];
  const b = builder.constant({type: operandType, dimensions: pb[1]}, new TestTypedArray(pb[0]));

  if (options === undefined) {
    options = {};
  }

  if (pc !== undefined) {
    if (typeof pc === 'number') {
      options.c = builder.constant(pc);
    } else {
      options.c = builder.constant({type: operandType, dimensions: pc[1]}, new TestTypedArray(pc[0]));
    }
  }

  const y = builder.gemm(a, b, options);
  const inputs = {'a': new TestTypedArray(pa[0])};
  const outputs = {'y': new TestTypedArray(sizeOfShape(expected[1]))};
  let graph;

  if (syncFlag) {
    graph = builder.build({y});
    context.compute(graph, inputs, outputs);
  } else {
    graph = await builder.buildAsync({y});
    await context.computeAsync(graph, inputs, outputs);
  }

  const nulp = PrecisionMetrics.IEPOE[operandType].gemm(pa[1], options);
  assert_array_approx_equals_ulp(outputs.y, expected[0][operandType], nulp, operandType);
}

// test data are random float64 numbers between [-1, 1) generated by invoking getRandomArbitrary(-1, 1)
// refering to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#getting_a_random_number_between_two_values
// A shape [3, 4]
const inputA = [
  -0.360921592038828,  -0.07925846945467674, 0.8736407270368782,  0.144456632858883,
  -0.5727564590008587, -0.05605486407501781, 0.5618192046724331,  0.9523204033011656,
  0.6521265334046897,  0.9913198542736765,   -0.9371378071929146, -0.4433339371721283,
];
// AT shape [4, 3]
const inputAT = [
  -0.360921592038828,   -0.5727564590008587,  0.6521265334046897,
  -0.07925846945467674, -0.05605486407501781, 0.9913198542736765,
  0.8736407270368782,   0.5618192046724331,   -0.9371378071929146,
  0.144456632858883,    0.9523204033011656,   -0.4433339371721283,
];
// B shape [4, 5]
const inputB = [
  -0.37958431231202505, -0.9441456654489362, -0.17361923909253862, -0.8491390965073751,   0.6995216934024131,
  0.7050471463885057,   0.7637121402304001,  0.2785586345435016,   0.17066236561726456,   0.5733487597787312,
  -0.34862826777967193, -0.5685210998866856, 0.12158916498669736,  0.21358731760120575,   -0.9668552717450334,
  0.6919947340930626,   -0.5071242526967215, 0.3806697246250086,   -0.004870190461895074, -0.6256411371751542,
];
// BT shape [5, 4]
const inputBT = [
  -0.37958431231202505, 0.7050471463885057,  -0.34862826777967193, 0.6919947340930626,
  -0.9441456654489362,  0.7637121402304001,  -0.5685210998866856,  -0.5071242526967215,
  -0.17361923909253862, 0.2785586345435016,  0.12158916498669736,  0.3806697246250086,
  -0.8491390965073751,  0.17066236561726456, 0.21358731760120575,  -0.004870190461895074,
  0.6995216934024131,   0.5733487597787312,  -0.9668552717450334,  -0.6256411371751542,
];
// C shape [3, 5]
const inputC = [
  0.6902649223861541,  -0.28031902087146987, 0.8190396843203964,
  0.5310302890734127,  0.23074000203065692,  -0.669949661652617,
  -0.6989441949433308, 0.29270378663475727,  -0.11553145685439503,
  0.4369736646175437,  0.15841539447894704,  0.07562104800977565,
  -0.2479556820691493, -0.8282518423341583,  -0.9666971098837789,
];
// C shape [1, 5]
const inputCBroadcast1 = [
  0.3441690781223872,    0.11610559241000606, 0.5622386682308855,
  -0.019415329530442005, 0.00802284054991187,
];
// C shape [3, 1]
const inputCBroadcast2 = [
  0.905762209983811, -0.7598234598671647, -0.20336496018610095,
];
// C is scalar
const inputCPositiveScalar = 0.6817309442438475;
const inputCNegativeScalar = -0.38121576376524624;
const inputCDefaultScalar = 0.0;

// random float32 numbers between (-1, 1) for alpha and beta
const alphaPositive = 0.6520302295684814;
const alphaNegative = -alphaPositive;
const alphaDefault = 1.0;
const betaPositive = 0.3881920576095581;
const betaZero = 0.0;
const betaNegative = -betaPositive;
const betaDefault = 1.0;

const expectedDefault = {
  float32: [
    -0.12349341064691544, -0.2897087335586548, 0.20180031657218933,
    0.47884124517440796,  -1.2329773902893066, 0.6410226821899414,
    -0.30439504981040955, 0.5146576166152954,  0.5921429395675659,
    -1.5718032121658325,  0.47131818532943726, 0.8989885449409485,
    -0.11979060620069504, -0.5825667977333069, 2.207993268966675,
  ],
};
const expectedByC = {
  float32: [
    0.5667715072631836,  -0.570027768611908,  1.020840048789978,
    1.009871482849121,   -1.0022374391555786, -0.028926968574523926,
    -1.0033392906188965, 0.807361364364624,   0.47661149501800537,
    -1.1348295211791992, 0.6297335624694824,  0.9746096134185791,
    -0.3677462935447693, -1.4108185768127441, 1.2412961721420288,
  ],
};
const expectedByCBroadcast1 = {
  float32: [
    0.22067567706108093,  -0.1736031472682953, 0.7640390396118164,
    0.4594259262084961,   -1.224954605102539,  0.9851917624473572,
    -0.18828946352005005, 1.0768963098526,     0.572727620601654,
    -1.563780426979065,   0.815487265586853,   1.0150941610336304,
    0.44244807958602905,  -0.6019821166992188, 2.2160160541534424,
  ],
};
const expectedByCBroadcast2 = {
  float32: [
    0.782268762588501,    0.6160534620285034,   1.10756254196167,
    1.384603500366211,    -0.32721519470214844, -0.11880075931549072,
    -1.064218521118164,   -0.24516582489013672, -0.1676805019378662,
    -2.3316266536712646,  0.26795321702957153,  0.6956235766410828,
    -0.32315555214881897, -0.7859317660331726,  2.0046284198760986,
    ],
};
const expectedByCPositiveScalar = {
  float32: [
    0.5582374930381775,  0.39202219247817993, 0.8835312128067017,
    1.1605721712112427,  -0.5512464642524719, 1.322753667831421,
    0.37733587622642517, 1.1963884830474854,  1.2738738059997559,
    -0.8900722861289978, 1.153049111366272,   1.5807194709777832,
    0.5619403123855591,  0.09916412830352783, 2.8897242546081543,
  ],
};
const expectedByCNegativeScalar = {
  float32: [
    -0.5047091841697693, -0.6709244847297668, -0.17941543459892273,
    0.0976254940032959,  -1.6141932010650635, 0.25980693101882935,
    -0.6856107711791992, 0.13344186544418335, 0.21092718839645386,
    -1.9530189037322998, 0.0901024341583252,  0.5177727937698364,
    -0.5010063648223877, -0.963782548904419,  1.826777458190918,
  ],
};
const expectedByAlphaPositive = {
  float32: [
    -0.08052143454551697, -0.18889884650707245, 0.1315799057483673,
    0.31221896409988403,  -0.8039385676383972,  0.41796615719795227,
    -0.19847477972507477, 0.33557233214378357,  0.3860951066017151,
    -1.0248632431030273,  0.3073136806488037,   0.5861676931381226,
    -0.07810709625482559, -0.37985116243362427, 1.4396783113479614,
  ],
};
const expectedByAlphaNegative = {
  float32: [
    0.08052143454551697,  0.18889884650707245,  -0.1315799057483673,
    -0.31221896409988403, 0.8039385676383972,   -0.41796615719795227,
    0.19847477972507477,  -0.33557233214378357, -0.3860951066017151,
    1.0248632431030273,   -0.3073136806488037,  -0.5861676931381226,
    0.07810709625482559,  0.37985116243362427,  -1.4396783113479614,
  ],
};
const expectedByCBeta = {
  float32: [
    0.1444619596004486,   -0.3985263705253601, 0.5197449922561646,
    0.6849830150604248,   -1.1434059143066406, 0.3809535503387451,
    -0.5757196545600891,  0.628282904624939,   0.547294557094574,
    -1.4021735191345215,  0.5328137874603271,  0.9283440113067627,
    -0.21604502201080322, -0.9040875434875488, 1.8327291011810303,
  ],
};
const expectedByCBroadcastBeta1 = {
  float32: [
    -0.25709712505340576, -0.3347800076007843, -0.016456276178359985,
    0.48637813329696655,  -1.2360918521881104, 0.5074189901351929,
    -0.34946632385253906, 0.2964010238647461,  0.5996798276901245,
    -1.5749176740646362,  0.3377144932746887,  0.8539173007011414,
    -0.33804720640182495, -0.5750299096107483, 2.204878807067871,
  ],
};
const expectedByCBroadcastBeta2 = {
  float32: [
    0.22811627388000488,  0.061900943517684937, 0.553409993648529,
    0.8304508924484253,   -0.8813676834106445,  0.3460652530193329,
    -0.5993524789810181,  0.2197001874446869,   0.2971855103969574,
    -1.8667606115341187,  0.39237353205680847,  0.8200438618659973,
    -0.19873526692390442, -0.6615114808082581,  2.1290485858917236,
  ],
};
const expectedByCScalarBeta = {
  float32: [
    -0.3881359398365021,  -0.554351270198822,  -0.0628422200679779,
    0.21419870853424072,  -1.497619867324829,  0.37638014554977417,
    -0.5690375566482544,  0.2500150799751282,  0.3275004029273987,
    -1.8364458084106445,  0.20667564868927002, 0.6343460083007812,
    -0.38443315029144287, -0.8472093343734741, 1.9433507919311523,
  ],
};
const expectedByAllOptions = {
  'float32': [
    -0.3484767973423004, -0.08008122444152832,  -0.1863647997379303,
    0.10607722401618958, -0.8935099840164185,   0.6780352592468262,
    0.0728498250246048,  0.22194704413414001,   0.43094348907470703,
    -1.1944929361343384, 0.24581807851791382,   0.5568122267723083,
    0.01814732700586319, -0.058330386877059937, 1.814942479133606,
  ],
};

// tests = {
//   purpose: [
//     [inputA, inputAShape],
//     [inputB, inputBShape],
//     [
//       [[expected, expectedShape], [inputC, inputCShape], options],
//       [[expected, expectedShape], inputCScalar, options],
//     ],
//   ],
// };
const tests = {
  'default options': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [[[expectedDefault, [3, 5]]]],
  ],
  'specified c option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [[[expectedByC, [3, 5]], [inputC, [3, 5]]]],
  ],
  'specified c (broadcast) option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedByCBroadcast1, [3, 5]], [inputCBroadcast1, [1, 5]]],
      [[expectedByCBroadcast2, [3, 5]], [inputCBroadcast2, [3, 1]]],
    ],
  ],
  'specified c (scalar) option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedByCPositiveScalar, [3, 5]], inputCPositiveScalar],
      [[expectedByCNegativeScalar, [3, 5]], inputCNegativeScalar],
      [[expectedDefault, [3, 5]], inputCDefaultScalar],
    ],
  ],
  'specified alpha option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedByAlphaPositive, [3, 5]], undefined, {alpha: alphaPositive}],
      [[expectedByAlphaNegative, [3, 5]], undefined, {alpha: alphaNegative}],
      [[expectedDefault, [3, 5]], undefined, {alpha: alphaDefault}],
    ],
  ],
  'specified beta option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedDefault, [3, 5]], undefined, {beta: betaPositive}],
      [[expectedDefault, [3, 5]], undefined, {beta: betaNegative}],
      [[expectedDefault, [3, 5]], undefined, {beta: betaDefault}],
      [[expectedDefault, [3, 5]], undefined, {beta: betaZero}],
    ],
  ],
  'specified c and beta options': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedByCBeta, [3, 5]], [inputC, [3, 5]], {beta: betaPositive}],
      [[expectedDefault, [3, 5]], [inputC, [3, 5]], {beta: betaZero}],
      [[expectedByCBroadcastBeta1, [3, 5]], [inputCBroadcast1, [1, 5]], {beta: betaNegative}],
      [[expectedByCBroadcastBeta2, [3, 5]], [inputCBroadcast2, [3, 1]], {beta: betaPositive}],
      [[expectedByCScalarBeta, [3, 5]], [[inputCPositiveScalar], [1]], {beta: betaNegative}],
      [[expectedByCScalarBeta, [3, 5]], [[inputCPositiveScalar], [1, 1]], {beta: betaNegative}],
      [[expectedByCScalarBeta, [3, 5]], inputCPositiveScalar, {beta: betaNegative}],
      [[expectedDefault, [3, 5]], inputCPositiveScalar, {beta: betaZero}],
    ],
  ],
  'specified aTranspose=true option': [
    [inputAT, [4, 3]],
    [inputB, [4, 5]],
    [
      [[expectedDefault, [3, 5]], undefined, {aTranspose: true}],
    ],
  ],
  'specified aTranspose=false option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedDefault, [3, 5]], undefined, {aTranspose: false}],
    ],
  ],
  'specified bTranspose=true option': [
    [inputA, [3, 4]],
    [inputBT, [5, 4]],
    [
      [[expectedDefault, [3, 5]], undefined, {bTranspose: true}],
    ],
  ],
  'specified bTranspose=false option': [
    [inputA, [3, 4]],
    [inputB, [4, 5]],
    [
      [[expectedDefault, [3, 5]], undefined, {bTranspose: false}],
    ],
  ],
  'specified all options': [
    [inputAT, [4, 3]],
    [inputB, [4, 5]],
    [
      [[expectedByAllOptions, [3, 5]], [inputC, [3, 5]], {alpha: alphaPositive, beta: betaNegative, aTranspose: true, bTranspose: false}],
    ],
  ],
};

let context;
let builder;

ExecutionArray.forEach(executionType => {
  const isSync = executionType === 'sync';
  if (self.GLOBAL.isWindow() && isSync) {
    return;
  }

  DeviceTypeArray.forEach(deviceType => {
    promise_setup(async () => {
      context = navigator.ml.createContext({deviceType});
      builder = new MLGraphBuilder(context);
    });

    OperandTypeArray.forEach(operandType => {
      for (let purpose in tests) {
        promise_test(async () => {
          const subTest = tests[purpose];
          let results = subTest[2];
          for (let i = 0; i < results.length; i++) {
            await testGemm(operandType, isSync, subTest[0], subTest[1], results[i][0], results[i][1], results[i][2]);
          }
        }, `test gemm with ${purpose} / ${deviceType} / ${executionType} / ${operandType}`);
      }
    });
  });
});