all:
	cp -f first-letter-characters-001-tmpl.xht first-letter-characters-001.xht
	python first-letter-characters-001-generator.py >> first-letter-characters-001.xht
	echo "</body></html>" >> first-letter-characters-001.xht

