#!/usr/bin/perl -w

use strict;

my %features = ();

sub read_features {
  my $fh;
  my $fn = shift;
  open $fh, $fn;
  while (<$fh>) {
    next unless s/^\s*\/\/ feature: //;
    /^([^(]*) \(([^)]*)\)(?: \(([^)]*)\))?$/ or die;
    my $key = "$1 ($2)";
    my $conditions = $3;
    $conditions = '' unless defined $conditions;
    $features{$key} = { } unless defined $features{$key};
    $features{$key}{$conditions} = [] unless defined $features{$key}{$conditions};
    push @{$features{$key}{$conditions}}, $fn;
  }
  close $fh;
}

sub read_tests {
  my $fh;
  my $fn;

  opendir $fh, '.';
  while ($fn = readdir $fh) {
    next unless -f $fn && $fn =~ /\.html$/;
    read_features($fn);
  }
  closedir $fh;
}

sub print_features {
  my $fh;
  open $fh, '>features.txt';
  print $fh "# This file is generated by gather-features.pl.\n\n";
  for my $key (sort keys %features) {
    print $fh "$key\n";
    for my $condition (sort keys %{$features{$key}}) {
      print $fh "  $condition\n" unless $condition eq '';
      for my $test (@{$features{$key}{$condition}}) {
        print $fh "    $test\n";
      }
    }
  }
  close $fh;
}

read_tests();
print_features();
