#!/usr/bin/env python3
import os
import re

re_testname = re.compile(r"^appearance-.+\d\d\d\.html$")
re_link_match = re.compile(r'<link rel="(mis)?match"')

files = {}
 
for filename in os.listdir():
    if os.path.isfile(filename) and re_testname.search(filename) and not filename in files:
        with open(filename, "r") as file:
            files[filename] = file.read()

warning = """<!-- DO NOT EDIT THIS FILE.
Edit the appearance-* file instead and then run:
    python3 appearance-build-webkit-reftests.py
-->
"""

for filename, text in files.items():
    if re_link_match.search(text):
        with open(filename.replace("appearance-", "webkit-appearance-"), "w") as outfile:
            outfile.write(warning + text.replace("appearance:", "-webkit-appearance:"))
