enum AddressSpace { "local", "private", "public" };

partial interface Document {
  readonly attribute AddressSpace addressSpace;
};

partial interface WorkerGlobalScope {
  readonly attribute AddressSpace addressSpace;
};
