
        [Constructor(optional InputDeviceCapabilitiesInit deviceInitDict)]
        interface InputDeviceCapabilities {
          readonly attribute boolean firesTouchEvents;
          readonly attribute boolean pointerMovementScrolls;
        };

        dictionary InputDeviceCapabilitiesInit {
          boolean firesTouchEvents = false;
          boolean pointerMovementScrolls = false;
        };

        partial interface UIEvent {
          readonly attribute InputDeviceCapabilities? sourceCapabilities;
        };

        partial dictionary UIEventInit {
          InputDeviceCapabilities? sourceCapabilities = null;
        };
