
      enum VisibilityState {
        "hidden", "visible", "prerender"
      };

      partial interface Document {
        readonly attribute boolean hidden;
        readonly attribute VisibilityState visibilityState;
        attribute EventHandler onvisibilitychange;
      };
