// https://wicg.github.io/sanitizer-api/

typedef (DOMString or DocumentFragment or Document) SanitizerInput;

[Exposed=Window, SecureContext]
 interface Sanitizer {
  [RaisesException] constructor();
  DocumentFragment sanitize(SanitizerInput input);
  DOMString sanitizeToString(SanitizerInput input);
};
