// https://wicg.github.io/sanitizer-api/

[
  Exposed=Window
] interface Sanitizer {
  [RaisesException] constructor(SanitizerConfig sanitizerConfig);
  DOMString sanitizeToString(DOMString input);
};

dictionary SanitizerConfig {};
