
partial interface NavigatorUserMedia {
    Promise<MediaStream> getDisplayMedia(optional MediaStreamConstraints constraints);
};
partial dictionary MediaTrackConstraintSet {
    ConstrainDOMString displaySurface;
    ConstrainBoolean   logicalSurface;
};
enum DisplayCaptureSurfaceType {
    "monitor",
    "window",
    "application",
    "browser"
};
