"use strict";
// https://console.spec.whatwg/org/#counting
// https://console.spec.whatwg/org/#timing

// toString() console label test strings
const toStringAssertionEnding = 'must call toString() on label when label is an object';
const toStringTestNameEnding = 'label gets converted to string via label.toString() when label is an object';

// toString error re-throwing console test strings
const toStringRethrowAssertionEnding = 'must re-throw any exceptions thrown by label.toString() conversion';
const toStringRethrowTestNameEnding = 'throws exceptions generated by erroneous label.toString() conversion';

const methods = ['count', 'countReset', 'time', 'timeLog', 'timeEnd'];

for (const method of methods) {
  test(() => {
    let labelToStringCalled = false;

    console[method]({
      toString() {
        labelToStringCalled = true;
      }
    });

    assert_true(labelToStringCalled, `${method}() ${toStringAssertionEnding}`);
  }, `console.${method}()'s ${toStringTestNameEnding}`);

  test(() => {
    assert_throws({name: 'Error'}, () => {
      console[method]({
        toString() {
          throw new Error('conversion error');
        }
      });
    }, `${method} ${toStringRethrowAssertionEnding}`);
  }, `console.${method}() ${toStringRethrowTestNameEnding}`);
}
