"""
Dynamic Python WPT server handler for Payment Method Manifest (PMM) testing.

This handler dynamically serves both Payment Method Identifier (PMI) endpoints and
Payment Method Manifest JSON files. It logs all incoming request metadata (HTTP method,
URL, headers) into `request.server.stash` under a test-specific `id` token.

Query Parameters:
  - `id`: Unique test run token (generated by token() in JS test).
  - `step`:
      - `pmi` (default): Serves the Payment Method Identifier endpoint. Returns HTTP 200
        and sets `Link: <...>; rel="payment-method-manifest"` pointing to step=manifest.
      - `manifest`: Serves the Payment Method Manifest JSON file.
"""

import json

STASH_PATH = "/payment-method-manifest/resources/"


def main(request, response):
    test_id = request.GET.get(b"id")
    step = request.GET.get(b"step", b"pmi")

    # Record incoming HTTP request metadata into server stash for test verification
    if test_id:
        stash = request.server.stash
        with stash.lock:
            logs = stash.take(test_id, path=STASH_PATH) or []
            header_dict = {
                k.decode("utf-8").lower(): v.decode("utf-8")
                for k, v in request.headers.items()
            }
            logs.append({
                "step": step.decode("utf-8"),
                "method": request.method.decode("utf-8"),
                "url": request.url.decode("utf-8"),
                "headers": header_dict,
            })
            stash.put(test_id, logs, path=STASH_PATH)

    # Step 1: Payment Method Identifier (PMI) Response
    if step == b"pmi":
        response.status = 200
        response.headers.set(b"Content-Type", b"text/html")
        manifest_target = f"/payment-method-manifest/resources/manifest-server.py?id={test_id.decode('utf-8')}&step=manifest"
        response.headers.set(
            b"Link",
            f'<{manifest_target}>; rel="payment-method-manifest"'.encode(
                "utf-8"
            ),
        )
        response.body = b"<!DOCTYPE html><html><body>PMI Endpoint</body></html>"

    # Step 2: Payment Method Manifest JSON Response
    elif step == b"manifest":
        response.status = 200
        response.headers.set(b"Content-Type", b"application/json")
        # Dynamically set supported_origins to the host origin to match local runner
        origin = f"{request.url_parts.scheme}://{request.url_parts.netloc}"
        response.body = json.dumps({"supported_origins": [origin]}).encode(
            "utf-8"
        )
