from gentestutils import genTestUtils

genTestUtils('yaml/element/color-space.yaml', '../element', '../element', 'templates-empty.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/compositing.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/conformance-requirements.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/drawing-images-to-the-canvas.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/drawing-rectangles-to-the-canvas.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/drawing-text-to-the-canvas.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/fill-and-stroke-styles.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/line-styles.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/meta.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/path-objects.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/pixel-manipulation.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/reset.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/scroll.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/shadows.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/text-styles.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/the-canvas-element.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/the-canvas-state.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/transformations.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)
genTestUtils('yaml/element/video.yaml', '../element', '../element', 'templates.yaml', 'name2dir.yaml', False)

genTestUtils('yaml/offscreen/compositing.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/conformance-requirements.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/drawing-images-to-the-canvas.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/drawing-rectangles-to-the-canvas.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/fill-and-stroke-styles.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/line-styles.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/meta.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/path-objects.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/pixel-manipulation.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/shadows.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/text.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/the-canvas-state.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/the-offscreen-canvas.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)
genTestUtils('yaml/offscreen/transformations.yaml', '../offscreen', '../offscreen', 'templates-offscreen.yaml', 'name2dir-offscreen.yaml', True)

