// DO NOT EDIT! This test has been generated by tools/gentest.py.
// OffscreenCanvas test in a worker:initial.colour
// Description:Initial state is transparent black
// Note:<p class="notes">Output should be transparent black (not transparent anything-else), but manual
verification can only confirm that it's transparent - it's not possible to make
the actual blackness visible.


importScripts("/resources/testharness.js");
importScripts("/common/canvas-tests.js");

var t = async_test("Initial state is transparent black");
t.step(function() {

var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');

_assertPixel(offscreenCanvas, 20,20, 0,0,0,0, "20,20", "0,0,0,0");

t.done();

});
done();
