name: Run tox on macOS
on:
  workflow_call:
    inputs:
      tox-directory:
        description: Directory to invoke tox in
        required: true
        type: string

# We never interact with the GitHub API, thus we can simply disable all
# permissions the GitHub token would have.
permissions: {}

jobs:
  results:
    name: Python ${{ matrix.python-version }}
    runs-on:
      - self-hosted
      - webkit-ews
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: Create hostedtoolcache for actions/setup-python
        # See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#macos
        run: |
          set -eux
          sudo mkdir -p /Users/runner/hostedtoolcache
          sudo chown "$USER:$( id -ng )" /Users/runner/hostedtoolcache
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run pip install tox
        run: |
          set -eux
          pip install tox
      - name: Run tox
        working-directory: ${{ inputs.tox-directory }}
        run: |
          set -eux
          tox -f "py$( echo ${{ matrix.python-version }} | sed 's/\.//' )"
