on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  wpt-fyi-notify:
    name: "Notify wpt.fyi"
    runs-on: ubuntu-24.04
    steps:
      - name: "wpt.fyi"
        if: ${{ !cancelled() }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://wpt.fyi/api/checks/github-actions/'
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: |
            ${{ format(
                  '{{"run_id": {0}, "owner": {1}, "repo": {2}, "artifact_name": {3}}}',
                  toJSON(github.run_id),
                  toJSON(github.repository_owner),
                  toJSON(github.event.repository.name),
                  toJSON(inputs.artifact-name)
            ) }}

      - name: "staging.wpt.fyi"
        if: ${{ !cancelled() }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://staging.wpt.fyi/api/checks/github-actions/'
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: |
            ${{ format(
                  '{{"run_id": {0}, "owner": {1}, "repo": {2}, "artifact_name": {3}}}',
                  toJSON(github.run_id),
                  toJSON(github.repository_owner),
                  toJSON(github.event.repository.name),
                  toJSON(inputs.artifact-name)
            ) }}
      - name: "Search for existing WPT comment"
        uses: peter-evans/find-comment@v3
        id: findcomment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Latest results on wpt.fyi

      - name: "Post latest results on WPT comment"
        if: steps.findcomment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            [Latest results on wpt.fyi](https://wpt.fyi/results/?label=pr_head&max-count=1&pr=${{ github.event.pull_request.number }})
